apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbl-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pbl-cicd-app
  template:
    metadata:
      labels:
        app: pbl-cicd-app
    spec:
      containers:
        - name: pbl-cicd-container
          image: pbl-cicd-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000